#!/bin/bash

HERE=$(dirname "${BASH_SOURCE[0]}")

if [ -f ~/.config/i3/config ]; then
  echo "An i3 config already exists on this computer!"
  exit 1
else
  mkdir -p ~/.config/i3
  cp $HERE/config ~/.config/i3/config
fi
